server:
  port: 8191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/somdba
    username: sanu
    password: sanu
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update